version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  web:
    build: ../backend
    restart: on-failure
    volumes:
      - ../backend:/backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: gunicorn wsgi:app --bind 0.0.0.0:5000

volumes:
  db:
    driver: local